// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmEqNyoY8SZMv2snm1Vsw658Z1DlV_P4o',
    appId: '1:852131848576:web:8e12d8424d5fb7c3ed6165',
    messagingSenderId: '852131848576',
    projectId: 'eco-market2',
    authDomain: 'eco-market2.firebaseapp.com',
    storageBucket: 'eco-market2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSd_wASdrASibNBURDCJdkjfGITwYEYKk',
    appId: '1:852131848576:android:f17ba1fe30c70d07ed6165',
    messagingSenderId: '852131848576',
    projectId: 'eco-market2',
    storageBucket: 'eco-market2.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmEqNyoY8SZMv2snm1Vsw658Z1DlV_P4o',
    appId: '1:852131848576:web:4c870f6cd48b7369ed6165',
    messagingSenderId: '852131848576',
    projectId: 'eco-market2',
    authDomain: 'eco-market2.firebaseapp.com',
    storageBucket: 'eco-market2.appspot.com',
  );
}
